### ISSUE TITLE
JAVA Programs Specially For Pattern Printing Are Needed. 

### ISSUE THREAD

**Issue by totally-somesh** [totally-somesh/Java-PlayGround#1]
~ Pattern Printing is one of the famous question asked for coding rounds. 
~ Let's gather few basic patterns including triangles / numbers / characters here.

**Comment by shubh8007** [comment]
Solve it -->
**Sandglass Star Pattern**
_Enter the number of rows: 5_

* * * * * 
 * * * * 
  * * * 
   * * 
    * 
    * 
   * * 
  * * * 
 * * * * 
* * * * *
